# Write your code here :-)
print('Salem, Alem!!!')
print('Atyn kim? ')
atym = input()
print('Tanysuga kuanyshtymyn, ' + atym)
print('Atyn uzyndygy: ')
print(len(atym), 'arip')
print('Zhasyn neshede? ')
zhasym = input()
print('Kelesi zhylda sen ' + str(int(zhasym) + 1) + ' zhaska tolasyn')
